services:
  db:
    image: postgres:15-alpine
    env_file: [./env/local.env]
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASS:-postgres}
      POSTGRES_DB: ${PGDB:-budget}
    ports: ["5432:5432"]
    volumes:
      - ./db/init_local.sql:/docker-entrypoint-initdb.d/01-init_local.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 20

  api:
    build: ./api
    env_file: [./env/local.env]
    environment:
      DB_HOST: ${DB_HOST_LOCAL:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${PGUSER:-postgres}
      DB_PASSWORD: ${PGPASS:-postgres}
      DB_NAME: ${PGDB:-budget}
      PORT: ${API_PORT:-3000}
    depends_on:
      db:
        condition: service_healthy
    ports: ["${API_PORT:-3000}:3000"]

  web:
    build: ./web
    env_file: [./env/local.env]
    depends_on:
      - api
    ports: ["${WEB_PORT:-8080}:80"]
