@startuml
title Mini Budget Tracker - User <-> Web VM <-> API VM <-> DB VM

actor User as U
participant "Web VM" as W
participant "API VM" as A
participant "DB VMMySQL" as D

note right of U
Private Networks:
- web (ip num i forgot)
- api (ip num i forgot)
- db  (ip num i forgot)
end note


== Load UI ==
U -> W: GET http://localhost:3000/
U <- W: HTML

== Health (?) ==
U -> W: GET /api/health
W -> A: proxy /api/health
A -> D: SELECT 1
D --> A: OK
A --> W: OK
W --> U: OK

== List transactions ==
U -> W: GET /api/transactions
W -> A: GET /transactions
A -> D: SELECT (need to add params later)
D --> A: trans
A --> W: rows?
W --> U: rows?
U -> U: Render list

== Add transaction ==
U -> U: Fill form
U -> W: POST /api/transactions
W -> A: POST /transactions
A -> A: ensure its all correct
A -> D: INSERT 
D --> A: created trans
A --> W: 201 created trans
W --> U: 201 created trans
U -> U: add trans to list

== Delete transaction ==
U -> U: Click × on item
U -> W: DELETE /api/transactions/{id}
W -> A: DELETE /transactions/{id}
A -> D: DELETE FROM transactions
D --> A: remove thing
A --> W: remove thing
W --> U: remove thing
U -> U: Remove thing from DOM

== Error path (?) ==
U -> W: GET /api/transactions
W -> A: proxy
A -> D: SELECT (something wrong?)
D --> A: ERROR (some error)
A --> W: (the error code?)
W --> U: (the error code?)
U -> U: Show "Starting up… retrying…"

@enduml
